# Generated by Django 2.2.6 on 2020-02-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_auto_20200205_1830'),
        ('redacoes', '0006_auto_20200205_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.FileField(help_text='Adicione um arquivo em formato PDF contendo o texto do aluno', upload_to='', verbose_name='Texto dissertativo argumentativo')),
                ('Nome_do_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Aluno')),
                ('Tema_da_redacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redacoes.Tema')),
            ],
        ),
    ]
