# Generated by Django 2.2.6 on 2020-02-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0002_redacao_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='teste',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
