# Generated by Django 2.2.6 on 2020-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0003_auto_20200211_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='teste',
            field=models.BooleanField(null=True),
        ),
    ]
