# Generated by Django 2.2.6 on 2020-02-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0004_auto_20200211_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='teste',
            field=models.BooleanField(default=False),
        ),
    ]
