# Generated by Django 2.2.6 on 2020-02-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0005_auto_20200211_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='teste',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
