# Generated by Django 2.2.6 on 2020-02-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0011_auto_20200211_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacao',
            name='c_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='redacao',
            name='c_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='redacao',
            name='c_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='redacao',
            name='c_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='redacao',
            name='c_5',
            field=models.IntegerField(default=0),
        ),
    ]
