# Generated by Django 3.0.4 on 2020-03-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correcao', '0012_auto_20200211_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='c_1',
            field=models.IntegerField(default=0, verbose_name='Competência 1'),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='c_2',
            field=models.IntegerField(default=0, verbose_name='Competência 2'),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='c_3',
            field=models.IntegerField(default=0, verbose_name='Competência 3'),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='c_4',
            field=models.IntegerField(default=0, verbose_name='Competência 4'),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='c_5',
            field=models.IntegerField(default=0, verbose_name='Competência 5'),
        ),
    ]
