# Generated by Django 3.0.4 on 2020-03-31 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20200205_1830'),
        ('redacoes', '0006_auto_20200205_1830'),
        ('correcao', '0013_auto_20200331_0036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Redacao',
            new_name='Texto',
        ),
    ]
