# Generated by Django 2.2.6 on 2020-02-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='arquivo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
