# Generated by Django 2.2.6 on 2020-02-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacoes', '0002_tema_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='arquivo',
            field=models.FileField(upload_to='', verbose_name='Texto 01'),
        ),
    ]
