# Generated by Django 2.2.6 on 2020-02-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacoes', '0004_auto_20200205_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='tema',
            field=models.CharField(help_text='Teste', max_length=150),
        ),
    ]
