# Generated by Django 2.2.6 on 2020-02-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacoes', '0005_auto_20200205_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='arquivo',
            field=models.FileField(help_text='Adicione um arquivo em formato PDF contendo todos os textos motivadores', upload_to='', verbose_name='Textos motivadores'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='tema',
            field=models.CharField(max_length=150),
        ),
    ]
