# Generated by Django 2.2.6 on 2020-01-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_turma', models.CharField(max_length=30)),
                ('ano', models.IntegerField(max_length=4)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Curso')),
            ],
        ),
    ]
