# Generated by Django 2.2.6 on 2020-02-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200205_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nome',
            new_name='nome_do_curso',
        ),
    ]
