# Generated by Django 2.2.6 on 2020-02-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20200205_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(help_text='Entre com o ano em que a turma está ativa. Ex.: 2020'),
        ),
    ]
